// Generated by GENAI

export const pitchR = (n: number, m: number) => (n * m) / 2;

export function gearPath(n: number, ro: number, ri: number) {
  const step = (Math.PI * 2) / n;
  const pts: string[] = [];
  for (let i = 0; i < n; i++) {
    const a = i * step;
    ([[-0.28, ri], [-0.16, ro], [0.16, ro], [0.28, ri]] as const).forEach(([k, r]) => {
      const t = a + step * k;
      pts.push(`${(Math.cos(t) * r).toFixed(2)},${(Math.sin(t) * r).toFixed(2)}`);
    });
  }
  return `M${pts.join("L")}Z`;
}

// phase (deg) for gear B so its teeth sit in A's gaps at contact angle theta (deg, A -> B)
export function meshPhase(nA: number, phA: number, nB: number, theta: number) {
  const sA = 360 / nA;
  const sB = 360 / nB;
  const u = ((((theta - phA) / sA) % 1) + 1) % 1;
  return theta + 180 - sB * (0.5 - u);
}

export type Placed = { x: number; y: number; n: number; ph: number };

export function attach(a: Placed, n: number, theta: number, m = 10): Placed {
  const d = pitchR(a.n, m) + pitchR(n, m);
  const t = (theta * Math.PI) / 180;
  return {
    x: +(a.x + Math.cos(t) * d).toFixed(2),
    y: +(a.y + Math.sin(t) * d).toFixed(2),
    n,
    ph: meshPhase(a.n, a.ph, n, theta),
  };
}
